[package]
name = "hermes"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.27.0", features = ["event-stream"] }
ratatui = "0.27.0"
tokio = { version = "1.39.1", features = ["full"] }
